# Don't print a new line at the start of the prompt
add_newline = false

format = """
$cmd_duration $directory$git_branch
  $character"""

[fill]
symbol = '-'
style = 'fg:#665566'

[character]
success_symbol = "[ ](bold fg:#F7AFFF)"
error_symbol = "[ ](bold fg:#D16D9E)"

[package]
disabled = true

[git_branch]
style = "bg:#F7AFFF"
symbol = "󰘬"
truncation_length = 12
truncation_symbol = ""
format = " 󰜥 [](bold fg:#F7AFFF)[$symbol $branch(:$remote_branch)](fg:#1E1B26 bg:#F7AFFF)[ ](bold fg:#F7AFFF)"

[git_commit]
commit_hash_length = 4
tag_symbol = " "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
cherry_pick = "[󰞋 PICKING](bold fg:#D16D9E)"

[git_status]
conflicted = " 󰞇 "
ahead = " 󰁝 "
behind = " 󰁅 "
diverged = " 󰹹 "
untracked = " 󰋗 "
stashed = " 󰏖 "
modified = " 󰏫 "
staged = '[++\($count\)](green)'
renamed = " 󰑕 "
deleted = " 󰆴 "

[hostname]
ssh_only = false
format = "[•$hostname](bg:#F7AFFF bold fg:#1E1B26)[](bold fg:#F7AFFF)"
trim_at = ".companyname.com"
disabled = false

[line_break]
disabled = false

[memory_usage]
disabled = true
threshold = -1
symbol = " "
style = "bold dimmed green"

[time]
disabled = true
format = '󰥔 [\[ $time \]]($style) '
time_format = "%T"

[username]
style_user = "bold bg:#F7AFFF fg:#1E1B26"
style_root = "red bold"
format = "[](bold fg:#F7AFFF)[$user]($style)"
disabled = false
show_always = true

[directory]
home_symbol = " "
read_only = "  "
style = "bg:#AE90C1 fg:#1E1B26"
#truncation_length = 2
#truncation_symbol = ".../"
truncation_length = 0
truncate_to_repo = false
truncation_symbol = ".../"
format = '[](bold fg:#AD89BE)[󰉋 → $path]($style)[](bold fg:#AD89BE)'

[directory.substitutions]
"Desktop" = "  "
"Documents" = "  "
"Downloads" = "  "
"Music" = " 󰎈 "
"Pictures" = "  "
"Videos" = "  "
"GitHub" = " 󰊤 "

[cmd_duration]
min_time = 0
format = '[](bold fg:#BA9CF9)[󰪢 $duration](bg:#BA9CF9 fg:#1E1B26)[](bold fg:#BA9CF9)'
